Add information on testing changes locally via docker
phpcommunity/phptestfest.org pull request #23
Opened 2017-07-11 14:33 UTC by rogeriopradoj

2017-07-11 14:37 UTC, ramsey commented
It looks like the latest version of etelej/jekyll was created over a year ago, so it doesn't include the latest versions of the gems in our `docs/Gemfile.lock` file.

2017-07-11 16:34 UTC, ramsey commented
This might be an alternative image to use. It looks popular and appears to be kept up-to-date. Our `Gemfile.lock` specifies github-pages version 141, and their latest image is from 6 days ago, using github-pages version 137.

https://hub.docker.com/r/starefossen/github-pages/

2017-07-11 17:22 UTC, ramsey commented
Unfortunately, I keep getting this error when trying to run that image:

```
/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.15.1/lib/bundler/spec_set.rb:87:in `block in materialize': Could not find minitest-5.10.2 in any of the sources (Bundler::GemNotFound)
from /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.15.1/lib/bundler/spec_set.rb:81:in `map!'
from /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.15.1/lib/bundler/spec_set.rb:81:in `materialize'
from /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.15.1/lib/bundler/definition.rb:159:in `specs'
from /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.15.1/lib/bundler/definition.rb:218:in `specs_for'
from /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.15.1/lib/bundler/definition.rb:207:in `requested_specs'
from /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.15.1/lib/bundler/runtime.rb:109:in `block in definition_method'
from /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.15.1/lib/bundler/runtime.rb:21:in `setup'
from /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.15.1/lib/bundler.rb:101:in `setup'
from /usr/local/bundle/gems/jekyll-3.4.3/lib/jekyll/plugin_manager.rb:36:in `require_from_bundler'
from /usr/local/bundle/gems/jekyll-3.4.3/exe/jekyll:9:in `<top (required)>'
from /usr/local/bundle/bin/jekyll:23:in `load'
from /usr/local/bundle/bin/jekyll:23:in `<main>'
```

2017-07-11 19:37 UTC, ramsey commented
@rogeriopradoj After being unable to get any of the GitHub Pages Docker images I found to work, I created our own solution. :smile:

We now have a Docker image for previewing GitHub Pages sites here: https://hub.docker.com/r/phpcommunity/github-pages/

This works well. I've already tested it:

```
cd docs/
docker run -v "$PWD":/usr/src/app -p "4000:4000" phpcommunity/github-pages
```

Please update your directions here. Thanks!

2017-07-11 19:38 UTC, ramsey requested changes

2017-07-11 19:38 UTC, ramsey commented on README.md
> +#### Via docker
Add "(preferred)" next to this.

2017-07-11 19:38 UTC, ramsey commented on README.md
> +docker run --rm -it -p 4000:4000 -v "$PWD":/app -w /app etelej/jekyll
Change to `docker run -v "$PWD":/usr/src/app -p "4000:4000" phpcommunity/github-pages`

2017-07-11 19:39 UTC, ramsey commented on README.md
> +docker run --rm -it -p 4000:4000 -v "$PWD":/app -w /app etelej/jekyll
You can also leave the `--rm -it` options in there, if you like.

2017-07-12 00:36 UTC, rogeriopradoj commented on README.md
> +#### Via docker
Nice. I was willing to do this from beginning ;-).

2017-07-12 00:38 UTC, rogeriopradoj commented on README.md
> +docker run --rm -it -p 4000:4000 -v "$PWD":/app -w /app etelej/jekyll
> You can also leave the --rm -it options in there, if you like.
I prefer to remove the container after execution. 😉

2017-07-12 03:15 UTC, rogeriopradoj commented
@ramsey please confirm it's fine now. Let me know if another adjust is needed.

Thanks!

2017-07-12 04:22 UTC, ramsey approved these changes
Looks great. Thanks!

2017-07-12 04:22 UTC, merged